### ISSUE TITLE
Questions about layernorm

### ISSUE THREAD

**Issue by xzqTest** [ShoufaChen/AdaptFormer#10]
Thanks for your excellent work.

I find there is an issue that the implementation does not match the paper (Fig.2 b):

In line 79 in **custom_modules.py**, the input of **adaptmlp** is not processed with **layernorm**. 

I have also checked the instantiation of **class Adapter**, it seems that the **adapter_layernorm_option** is always set as "None" according to **tuning_config** in **main_image.py** or **main_video.py**. So the input is also not normed in **Adapter**.

I wondered if the code is correct, or the Fig.2b needs to be revised.

**Comment by ShoufaChen** [comment]
Good catch. Please refer to https://github.com/ShoufaChen/AdaptFormer/issues/9.

Thank you.
