### ISSUE TITLE
missing keys when load pre-trained checkpoint

### ISSUE THREAD

**Issue by ZipengFeng** [ShoufaChen/AdaptFormer#11]
Thanks for sharing codes for your excellent work!  When I run `main_image.py ` with the provided pre-trained checkpoint, I got some info as follows:

![image](https://user-images.githubusercontent.com/24842821/184544910-26890491-fad8-4454-8604-4c76c9510144.png)

For example, one of the key in the model`s state_dict is **blocks.0.fc1.weight** , but **blocks.0.mlp.fc1.weight** in the pre-trained checkpoint.  And I got poor results when I train cifar100.

 I suspect that I am doing something wrong. Could you help me? Thank you very much!

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

Did you get the `mae_pretrain_vit_base.pth` from MAE official repo?

You should use our provided checkpoint in https://github.com/ShoufaChen/AdaptFormer/releases/tag/v0.1.

We do some key-mapping as introduced in https://github.com/ShoufaChen/AdaptFormer/blob/main/PRETRAIN.md.

**Comment by ZipengFeng** [comment]
Thanks！ It works!
