### ISSUE TITLE
Questions about data split.

### ISSUE THREAD

**Issue by luogen1996** [ShoufaChen/AdaptFormer#18]
Thanks for your great work.  I would like to know on which data split (val or test) the performance is reported in your paper.  I notice that the final testing seems to be conducted  on validation set.
```
mode = 'test'
anno_path = os.path.join(args.data_path, 'val.csv') 
```

**Comment by ShoufaChen** [comment]
Yes, for SSv2 dataset, the final testing is also conducted on `val.csv`, which follows the VideoMAE settings.
