### ISSUE TITLE
Data split for HMDB51 dataset

### ISSUE THREAD

**Issue by Maikuki** [ShoufaChen/AdaptFormer#3]
The paper says "HMDB51 is composed of 6,849 videos with 51 categories, making a split of 3.5k/1.5k train/val videos." Do you conduct random split on the 6849 videos? And how can I get the test videos?

**Comment by ShoufaChen** [comment]
Hi, thanks for your interest.

The data split for HMDB51 follows the official instruction [here](https://serre-lab.clps.brown.edu/wp-content/uploads/2013/10/split_readme.txt):
```
There are totally 153 files in this folder, 
[action]_test_split[1-3].txt  corresponding to three splits reported in the paper.
The format of each file is
[video_name] [id]
The video is included in the training set if id is 1
The video is included in the testing set if id is 2
The video is not included for training/testing if id is 0
There should be 70 videos with id 1 , 30 videos with id 2 in each txt file.
```

The split files can be found via http://serre-lab.clps.brown.edu/wp-content/uploads/2013/10/test_train_splits.rar

We only use `split1` in our experiments following VideoMAE.

**Comment by Maikuki** [comment]
I get it! Thanks for your response.
