### ISSUE TITLE
How can we get more pre-trained checkpoints?

### ISSUE THREAD

**Issue by rshaojimmy** [ShoufaChen/AdaptFormer#7]
Hi,

May I ask where can we get more pre-trained checkpoints, such as vit_base_patch16_384, which can be directly loaded based on current code?

Thanks.

**Comment by ShoufaChen** [comment]
Hi, do you need a pre-trained checkpoint for video or image?  They have minor differences such as the first patch embedding layer (3D conv for video while 2D conv for image).

**Comment by rshaojimmy** [comment]
Hi,

I just need pre-trained checkpoints for images with different ViT strutures. May I know do you download these checkpoints via links such as https://github.com/pengzhiliang/Conformer/blob/main/vision_transformer.py#L32-L80

Thanks.

**Comment by ShoufaChen** [comment]
I used timm provided checkpoints with small key-mappings as introduced in https://github.com/ShoufaChen/AdaptFormer/blob/main/PRETRAIN.md.

I intend to upload these processed checkpoints this weekend.

**Comment by rshaojimmy** [comment]
Sure, thanks. Hope to see the image code with pre-trained weights process as well soon. Thanks so much.

**Comment by ShoufaChen** [comment]
Hi, @rshaojimmy 

Image code and pre-trained weights are released at https://github.com/ShoufaChen/AdaptFormer/pull/8.

**Comment by ShoufaChen** [comment]
Updated Table 1.
<img width="556" alt="image" src="https://user-images.githubusercontent.com/28682908/173215664-1410d89f-cad4-4d84-8c6b-aae1081978c4.png">

**Comment by rshaojimmy** [comment]
Thanks so much!
